let h1saludo = document.querySelector("#saludo")
let nombre = prompt("ingrese su nombre")
let h2edad = document.querySelector("#edad")
let edad = Number (prompt("ingrese su edad"))
//edad= Number (edad)
h1saludo.innerHTML= ("Hola " + nombre )
h2edad.innerHTML= "su edad en 10 años será " + (edad + 10)
console.log(h1saludo)
console.log(h2edad)